### ISSUE TITLE
`SemanticLidarSensor` does not filter out parent

### ISSUE THREAD

**Issue by adamlm** [usdot-fhwa-stol/carla-sensor-lib#9]
### Summary

The `SemanticLidarSensor` does not filter out its parent, causing the parent to always be reported as a detection. This may or may not be intended.

### Commit

`develop`

### Expected Behavior

The `SemanticLidarSensor` does not report its parent.

### Actual Behavior

The `SemanticLidarSensor` reports its parent.

### Steps to Reproduce the Actual Behavior

1. Attach a `SemanticLidarSensor` instance to a parent actor
2. Print out lidar's detections

### Related Work

[CDAR-490](https://usdot-carma.atlassian.net/browse/CDAR-490)

[CDAR-490]: https://usdot-carma.atlassian.net/browse/CDAR-490?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by MishkaMN** [comment]
Resolved with this commit
https://github.com/usdot-fhwa-stol/carla-sensor-lib/commit/df7cb51d7c259b22f007684cb01b17e46aa9f377
